-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "addressLine1" TEXT,
ADD COLUMN     "addressLine2" TEXT,
ADD COLUMN     "bankAccountHolderName" TEXT,
ADD COLUMN     "bankAccountLast4" TEXT,
ADD COLUMN     "bankCountry" TEXT,
ADD COLUMN     "bankCurrency" TEXT,
ADD COLUMN     "bankName" TEXT,
ADD COLUMN     "bankRoutingLast4" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "commissionBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "commissionRatePercent" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN     "contactPhone" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "lastCommissionAt" TIMESTAMP(3),
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "stripeAccountId" TEXT,
ADD COLUMN     "stripeAccountType" TEXT DEFAULT 'express',
ADD COLUMN     "stripeChargesEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stripeOnboardingCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stripePayoutsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "subscriptionPaymentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalCommissionEarned" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalCommissionPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "website" TEXT;
