-- AlterTable
ALTER TABLE "User" ADD COLUMN     "apg" DOUBLE PRECISION,
ADD COLUMN     "blk" DOUBLE PRECISION,
ADD COLUMN     "ppg" DOUBLE PRECISION,
ADD COLUMN     "rpg" DOUBLE PRECISION,
ADD COLUMN     "spg" DOUBLE PRECISION;
